# frozen_string_literal: true

raise "Package verification must eager-load at boot" unless Rails.application.config.eager_load
raise "Loaded checkout source instead of installed package" unless File.realpath(Gem.loaded_specs.fetch("ecs_on_rails").full_gem_path).start_with?(File.realpath(ENV.fetch("ECS_SMOKE_GEM_HOME")) + "/")
raise "Unexpected JSON major" unless Gem.loaded_specs.fetch("json").version < Gem::Version.new("3")
raise "Expected one install migration" unless Rails.root.glob("db/migrate/*.rb").size == 1

# The actual README runner created these rows in a separate process. Verify
# persisted outcomes so an attractive but non-working example fails CI.
contact = Contact.sole
raise "Flat assignment lost a name/email" unless contact.name.initials == "AL" && contact.email_address == "ada@example.test"
raise "Labelled slot was lost" unless contact.home_address.country == "AU"
raise "Marker query failed" unless Contact.with_marker(:featured).sole.id == contact.id
raise "Component query failed" unless Contact.with_component(Address, prefix: :home, country: "AU").sole.id == contact.id
raise "Relationship/inverse failed" unless contact.notes.sole.body == "Met at Ruby meetup" && Note.sole.author == contact
raise "Primary value failed" unless Company.sole.name == "Analytical Engines"
raise "System missed an entity type" unless EmailDirectory.call == ["ada@example.test", "hello@example.test"]
raise "Reading persisted the avatar" if contact.avatar_image.persisted? || contact.has?(Image, prefix: :avatar)
empty = Contact.create!
raise "Virtual default changed" unless empty.email.verified == false && !empty.email.persisted?
empty.save!
raise "Saving a virtual default inserted a row" if Email.exists?(entity_id: empty.id)
empty.destroy!

# This class is generated by the exact Person command and is never rewritten
# from a README file block. Persist both slots to catch shared-reader mistakes.
person = Person.create!(name_given: "Grace", mobile_phone_e164: "+12025550101",
                        work_phone_e164: "+12025550102", home_address_country: "AU")
raise "Generated Phone slots overlap" unless person.reload.mobile_phone.e164 == "+12025550101" && person.work_phone.e164 == "+12025550102"
raise "Generated Address slot failed" unless Person.with_component(Address, prefix: :home, country: "AU").sole == person
raise "Entity generator emitted a migration" unless Rails.root.glob("db/migrate/*.rb").size == 1
person.destroy!

Rails.application.eager_load!
require "rack/mock"
response = Rack::MockRequest.new(Rails.application).get("/", "HTTP_HOST" => "localhost")
raise "Rendered quickstart failed: #{response.status}" unless response.status == 200 && response.body.include?("Ada: ada@example.test")
puts "Packaged quickstart, components, slots, marker, relationship and rendered page passed."
