# frozen_string_literal: true

# Moves markers onto the shared `markers` table (ADR-0018 §4).
#
# A marker has no state: an entity IS a moderator exactly when its row exists.
# Every marker is a row here, the slot being the marker name, so declaring
# `marker :moderator` no longer needs a table of its own.
#
# Generated by `rails g ecs_rails:upgrade`, which found the tables below by
# their shape: component tables with no attribute columns at all. Review the
# list before running — each is copied into `markers` under its singular name
# and dropped. Irreversible, hence `up`/`down`.
class EcsRailsSharedMarkers < ActiveRecord::Migration[8.1]
  def up
    create_table :markers, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
      t.uuid   :entity_id, null: false
      t.string :slot,      null: false, default: ""
      t.timestamps
    end
    add_index :markers, [:entity_id, :slot], unique: true
    add_foreign_key :markers, :entities, column: :entity_id, on_delete: :cascade

    # administrators -> slot "administrator"
    execute <<~SQL
      INSERT INTO markers (id, entity_id, slot, created_at, updated_at)
      SELECT id, entity_id, 'administrator', created_at, updated_at
      FROM administrators
    SQL
    drop_table :administrators

    # moderators -> slot "moderator"
    execute <<~SQL
      INSERT INTO markers (id, entity_id, slot, created_at, updated_at)
      SELECT id, entity_id, 'moderator', created_at, updated_at
      FROM moderators
    SQL
    drop_table :moderators
  end

  def down
    raise ActiveRecord::IrreversibleMigration, "the per-marker tables were dropped"
  end
end
