# frozen_string_literal: true

# Adds the slot column to every existing component table (RFC-0014 / ADR-0015).
#
# A component may now be declared more than once on an entity under distinct
# labels (`component Address, prefix: :business`); the `slot` column is
# the label, "" for the singular default. The one-per-entity unique index
# (ADR-0005) becomes one-per-(entity, slot). Safe on existing data: every row
# already here is the single slot = "" row, so the new index admits exactly what
# the old one did.
#
# Generated by `rails g ecs_rails:upgrade`, which found these tables by looking
# for an entity_id column and no slot column. Three stale tables the dev
# database still carried from before `relates_to` (authorships, member_users,
# member_groups — in db/schema.rb but created by no migration) were removed by
# hand so this file runs from an empty database; the schema was then rebuilt
# from the migration chain.
class EcsRailsAddSlots < ActiveRecord::Migration[8.1]
  def change
    add_column :administrators, :slot, :string, null: false, default: ""
    remove_index :administrators, column: :entity_id, unique: true
    add_index :administrators, [:entity_id, :slot], unique: true

    add_column :avatars, :slot, :string, null: false, default: ""
    remove_index :avatars, column: :entity_id, unique: true
    add_index :avatars, [:entity_id, :slot], unique: true

    add_column :bios, :slot, :string, null: false, default: ""
    remove_index :bios, column: :entity_id, unique: true
    add_index :bios, [:entity_id, :slot], unique: true

    add_column :bodies, :slot, :string, null: false, default: ""
    remove_index :bodies, column: :entity_id, unique: true
    add_index :bodies, [:entity_id, :slot], unique: true

    add_column :comment_authors, :slot, :string, null: false, default: ""
    remove_index :comment_authors, column: :entity_id, unique: true
    add_index :comment_authors, [:entity_id, :slot], unique: true

    add_column :comment_posts, :slot, :string, null: false, default: ""
    remove_index :comment_posts, column: :entity_id, unique: true
    add_index :comment_posts, [:entity_id, :slot], unique: true

    add_column :descriptions, :slot, :string, null: false, default: ""
    remove_index :descriptions, column: :entity_id, unique: true
    add_index :descriptions, [:entity_id, :slot], unique: true

    add_column :emails, :slot, :string, null: false, default: ""
    remove_index :emails, column: :entity_id, unique: true
    add_index :emails, [:entity_id, :slot], unique: true

    add_column :likes, :slot, :string, null: false, default: ""
    remove_index :likes, column: :entity_id, unique: true
    add_index :likes, [:entity_id, :slot], unique: true

    add_column :membership_groups, :slot, :string, null: false, default: ""
    remove_index :membership_groups, column: :entity_id, unique: true
    add_index :membership_groups, [:entity_id, :slot], unique: true

    add_column :membership_users, :slot, :string, null: false, default: ""
    remove_index :membership_users, column: :entity_id, unique: true
    add_index :membership_users, [:entity_id, :slot], unique: true

    add_column :moderators, :slot, :string, null: false, default: ""
    remove_index :moderators, column: :entity_id, unique: true
    add_index :moderators, [:entity_id, :slot], unique: true

    add_column :names, :slot, :string, null: false, default: ""
    remove_index :names, column: :entity_id, unique: true
    add_index :names, [:entity_id, :slot], unique: true

    add_column :post_authors, :slot, :string, null: false, default: ""
    remove_index :post_authors, column: :entity_id, unique: true
    add_index :post_authors, [:entity_id, :slot], unique: true

    add_column :publish_states, :slot, :string, null: false, default: ""
    remove_index :publish_states, column: :entity_id, unique: true
    add_index :publish_states, [:entity_id, :slot], unique: true

    add_column :roles, :slot, :string, null: false, default: ""
    remove_index :roles, column: :entity_id, unique: true
    add_index :roles, [:entity_id, :slot], unique: true

    add_column :titles, :slot, :string, null: false, default: ""
    remove_index :titles, column: :entity_id, unique: true
    add_index :titles, [:entity_id, :slot], unique: true
  end
end
