# frozen_string_literal: true

module EcsRails
  # Component presence as a first-class operation: add / has? / remove.
  #
  # Implements RFC-0009, decided by ADR-0009. Surfaced by the demo: a marker
  # component (Moderator, Administrator) carries no state, so it is never
  # `ecs_dirty?` (ADR-0003 excludes entity_id as identity), and RFC-0006's save
  # cascade therefore never writes it. The natural path does nothing at all:
  #
  #   user.moderator            # a virtual Moderator
  #   user.save!                # writes no moderators row — a marker is never dirty
  #   user.moderator.persisted? # => false, forever
  #
  # Presence cannot be inferred from lazy state (reading must stay free, RFC-0006)
  # and a marker has nothing to dirty, so presence is its own verb:
  #
  #   user.add(Moderator)     # persist the row now (idempotent, validated)
  #   user.has?(Moderator)    # => true — a row exists
  #   user.moderator?         # => the same question, per-component sugar (DSL)
  #   user.remove(Moderator)  # destroy the row (idempotent)
  #
  # These are useful for *every* component — `has?(Email)`, `remove(Avatar)` —
  # not just empty ones; a marker is simply the case where presence is the only
  # state (ADR-0009). Mirrors Flecs' add/has/remove vocabulary.
  #
  # This module is the entity side. The `<reader>?` predicate is generated per
  # component by the DSL, into generated_component_methods (see
  # EcsRails::DSL#define_component_predicate); it is just `has?(ThatComponent)`.
  #
  # Labelled slots (RFC-0014) add an optional `prefix:` to all three verbs —
  # `add(PostalAddress, prefix: :business)` — and the per-slot predicate
  # `user.business_address?`. Omitted, `prefix:` means the default slot, so
  # every singular call reads exactly as before.
  #
  # Markers (ADR-0018 §4) add a Symbol form: `add(:moderator)` / `has?` /
  # `remove` name a marker declared with `marker :moderator`, which is the
  # `Marker` component in slot "moderator". `user.moderator?` is that `has?`.
  module Presence
    # The entity side of presence: `add` / `has?` / `remove`.
    #
    # Included into {EcsRails::Entity}, so every entity answers these. The
    # per-component `<reader>?` predicate (`user.moderator?`) is generated by
    # {EcsRails::DSL} and is exactly {#has?}.
    #
    # @example
    #   user.add(Moderator)     # persist the row now (idempotent, validated)
    #   user.has?(Moderator)    # => true
    #   user.remove(Moderator)  # destroy the row (idempotent)
    module Entity
      extend ActiveSupport::Concern

      # Ensures a row exists for `component_class` on this entity and returns the
      # now-persisted instance (RFC-0009).
      #
      # Immediate, not deferred to the next save: the whole reason `add` exists
      # is that the save cascade never persists a marker. Idempotent: an existing
      # row is returned untouched, never a second INSERT — the unique entity_id
      # index (ADR-0005) would forbid one, and correctness should not depend on
      # catching that. Validated: it uses `save!`, so `add(Email)` raises
      # RecordInvalid (address is required) while `add(Moderator)` always
      # succeeds. You cannot add an empty required component (ADR-0009).
      #
      # @example A marker, which the save cascade would never write
      #   user.add(Moderator)     # INSERTs the row now
      #   user.moderator?         # => true
      #
      # @example Validation still applies
      #   user.add(Email)         # raises: Email#address is required
      #
      # @example A labelled slot (RFC-0014)
      #   user.add(PostalAddress, prefix: :business)
      #   user.business_address?  # => true
      #
      # @example A marker, by name (ADR-0018 §4)
      #   user.add(:moderator)
      #   user.moderator?         # => true
      #
      # @param component_class [Class<EcsRails::Component>, Symbol] a component
      #   this entity declares, or the name of a marker it declares
      # @param prefix [Symbol, String, nil] the slot label; nil for the default
      #   slot. Not accepted with a marker name.
      # @return [EcsRails::Component] the persisted component instance
      # @raise [EcsRails::InvalidComponent] if the entity does not declare it in
      #   that slot
      # @raise [ActiveRecord::RecordInvalid] if the component is invalid — you
      #   cannot add an empty required component (ADR-0009)
      # @see #has?
      # @see #remove
      def add(component_class, prefix: nil)
        name = ecs_presence_declaration(component_class, prefix).reader_name

        # The reader goes through RFC-0006's memo. When no row exists on this
        # instance it loads one (a SELECT) or builds a virtual; when a row does
        # exist — including one this instance already added — it is already the
        # persisted instance, so we return it and no second INSERT is attempted.
        component = public_send(name)
        return component if component.persisted?

        # A virtual instance: persist it. entity_id is restamped for the same
        # reason the cascade does (RFC-0006) — on a freshly built virtual for a
        # new entity it may not have been set yet. The memo now holds this same,
        # persisted instance, so a later `entity.moderator` answers from it with
        # no further query.
        component.entity_id = id
        component.save!
        component
      end

      # True iff a row exists for `component_class` on this entity (RFC-0009).
      #
      # Side-effect-free, like `valid?` (RFC-0007): it never materialises,
      # persists, or dirties anything. It consults RFC-0006's memo first — a
      # component dirtied-and-saved on this instance is present without a fresh
      # query — and otherwise issues a bare existence check (SELECT ... EXISTS),
      # a load of nothing.
      #
      # The DSL also generates a per-component predicate, so `user.moderator?`
      # asks exactly this question.
      #
      # @example
      #   user.has?(Moderator)  # => true
      #   user.moderator?       # => the same question, generated per component
      #
      # @param component_class [Class<EcsRails::Component>, Symbol] a component
      #   this entity declares, or the name of a marker it declares
      # @param prefix [Symbol, String, nil] the slot label; nil for the default slot
      # @return [Boolean] whether a persisted row exists in that slot
      # @raise [EcsRails::InvalidComponent] if the entity does not declare it in
      #   that slot
      # @see #add
      # @see #remove
      def has?(component_class, prefix: nil)
        declaration = ecs_presence_declaration(component_class, prefix)
        name = declaration.reader_name

        # Memo first: if this instance already loaded (and persisted) the
        # component, the answer is known without touching the database.
        cached = @ecs_components&.[](name)
        return true if cached&.persisted?

        # Then the has_one itself. Once ActiveRecord has loaded it — by a
        # preload (`includes_components(Marker)` on a list view) or by an earlier
        # read through the reader — its target is authoritative for this
        # instance, present or absent, exactly as any association cache is; a
        # row written elsewhere since is stale until `reload`, as it would be
        # for `user.email`. This is what makes a page of marker badges cost no
        # queries after one preload (RFC-0016). A virtual memo entry alone does
        # not decide it: `remove` on an absent marker leaves one behind without
        # loading anything, and the association says so.
        association = association(name)
        return !association.target.nil? if association.loaded?

        # Bare existence check: no row is instantiated, so nothing is loaded and
        # nothing is dirtied. One query per component, as everywhere else in the
        # gem (architecture.md §7 non-goal: query optimisation). Slot-scoped, so
        # a `business_address` row does not answer for `postal_address`.
        declaration.component_class.where(entity_id: id, slot: declaration.slot).exists?
      end

      # Destroys the row for `component_class` if present, and resets the reader
      # to a virtual default instance — exactly RFC-0006's `component.destroy`
      # semantics. Idempotent when absent. Returns the entity (RFC-0009).
      #
      # @example
      #   user.remove(Moderator)  # DELETEs the row; no-op if there was none
      #   user.moderator          # => #<Moderator> — virtual again, not nil
      #
      # @param component_class [Class<EcsRails::Component>, Symbol] a component
      #   this entity declares, or the name of a marker it declares
      # @param prefix [Symbol, String, nil] the slot label; nil for the default slot
      # @return [self] the entity, for chaining
      # @raise [EcsRails::InvalidComponent] if the entity does not declare it in
      #   that slot
      # @see #add
      # @see #has?
      def remove(component_class, prefix: nil)
        name = ecs_presence_declaration(component_class, prefix).reader_name

        # Reach the component through the reader so a present row is loaded with
        # its callbacks intact. `component.destroy` fires Lazy::Component's
        # after_destroy, which calls #ecs_forget_component here — dropping the
        # memo and nilling the association, so the next read rebuilds a virtual.
        # When nothing is there to destroy the read leaves a virtual in the memo,
        # which is already the reset state, so remove is idempotent.
        component = public_send(name)
        component.destroy if component.persisted?
        self
      end

      private

      # Resolves a declared (component, slot) — or a marker name — to its
      # declaration, or raises.
      #
      # `add`/`has?`/`remove` accept only a component the entity actually
      # declares (RFC-0009), in a slot it declares it under (RFC-0014), or the
      # Symbol name of a marker it declares (ADR-0018 §4); anything else — an
      # undeclared component, an undeclared slot, an unknown marker, or a class
      # that is not a component at all — is InvalidComponent, checked before any
      # database work. The lookup already accounts for inheritance
      # (DSL#declaration_for walks the ancestry), so a subclass sees its parents'
      # components too.
      def ecs_presence_declaration(component_class, prefix)
        if component_class.is_a?(Symbol) || component_class.is_a?(String)
          raise ArgumentError, "a marker name takes no prefix: (got #{prefix.inspect})" unless prefix.nil?

          declaration = self.class.marker?(component_class) &&
                        self.class.declaration_for(EcsRails.config.marker_class_name.constantize,
                                                   prefix: component_class)
          return declaration if declaration

          known = self.class.marker_names
          raise InvalidComponent,
                ":#{component_class} is not a marker of #{self.class.name}. #{self.class.name} marks: " \
                "#{known.empty? ? 'none' : known.map { |n| ":#{n}" }.join(', ')}."
        end

        declaration =
          component_class.is_a?(Class) && self.class.declaration_for(component_class, prefix: prefix)
        return declaration if declaration

        where = prefix.nil? ? "" : " in slot #{prefix.to_s.inspect} (prefix: :#{prefix})"
        raise InvalidComponent,
              "#{component_class.inspect} is not a component of #{self.class.name}#{where}"
      end
    end
  end
end
