# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rake", "~> 13.0"

group :development, :test do
  gem "pg", "~> 1.5"
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.66", require: false
  gem "rubocop-rspec", "~> 3.0", require: false
end
